### ISSUE TITLE
Проблемы со scrollbar'ом и Aligments

### ISSUE THREAD

**Issue by Gunirs** [StannisMod/gext#3]
Привет.
В принципе описывал все, но все же вот ряд проблем, которые я обнаружил:

**1.** При добавлении вертикального скролла для GList скролл работает до тех пор, пока мы используем примитивный GLabel. Как только мы добавляем что-то более сложное (начиная с кнопки и заканчивая контейнерами с разными элементами) мы получаем такую картину, что элементы словно скроллят сами себя.
Поведение записано на видео: https://youtu.be/9gKUyQlwEBU

**Как пытались решить:** как и обсуждалось ранее, но все же напомню, было предположение что проблема связана с добавлением Aligments. Пытались решить путем создания компонента от BasycLayout что не увенчалось успехом. Элемент, не имея поддержки скролла продолжал также скроллить сам себя. 

**2.** Не менее важная проблема, с которой довелось столкнуться - это неполноценная работоспособность компонента GButton при использовании Aligments. При таком раскладке компонент сам по себе существует, имеет hover, но действия, которые мы передаем консьюмеру не выполняются. У меня сложилось ощущение, что он сместил _к черту на куличики_ координаты для проверки клика мышкой.

**3.** Конфликт между placeAt и Aligments у компонента GButton. При позиционировании элемента с помощью Aligments и использовании при этом placeAt для размещения на указанных координатах (хотел использовать с целью смещения) кнопка просто исчезает с монитора _канула в небытие_.

**4.** Даже если использовать GList со скроллбаром для вывода компонентов GLabel (единственное что возможно на данный момент по идее) и при этом, имея на экране отрисованный GUI изменить размер окна игры мы получим глючный скролл. При попытке скролла после таких действий его будет _швырять_ вверх/вниз постоянно.
Важный момент: все это происходит даже при условии того, что при изменении размеров окна я очищаю layout путем вызова layout().clear(). Выполняю при каждом initLayout(), ибо он вызывается каждый раз при изменении окна игры.

Пока все что могу описать, ибо дальнейшее использование библиотеки на данный момент невозможно в каких-либо проектах куда необходимо добавить скроллинг элементов по причине этих ошибок.

**Comment by StannisMod** [comment]
Все указанные проблемы закрыты коммитами [1](https://github.com/StannisMod/gext/commit/1d1cbbefc1612b64a0223330e4cc6b69d0230f28), [2](https://github.com/StannisMod/gext/commit/715adb154a2f1f7b868f0993f7b8ed52d7dc9340) и [3](https://github.com/StannisMod/gext/commit/77f7e45ce8712e58819e876beae185937d0aa105). За дополнительными пояснениями можно переоткрыть `issue`.
