### ISSUE TITLE
Поддержка новых версий

### ISSUE THREAD

**Issue by bigenergy** [StannisMod/gext#4]
Приветствую, стоит ли ожидать поддержку 1.16.5 и 1.18.2?

**Comment by StannisMod** [comment]
И я. Вижу, запрос появился. Да, в ближайшее время собираюсь выпустить адаптеры под все новые версии.

**Comment by StannisMod** [comment]
Дело пойдет быстрее, если у меня появится по ним консультант. Я не писал на новых версиях.

**Comment by StannisMod** [comment]
Version 1.5.1.0-SNAPSHOT introduced support for 1.16-1.19.
